window.MathJax = {
    TeX: {
        TagSide: "left",
        TagIndent: "0em",
        Macros: {
            bAlg: "\\mathbf{Alg}",
	    blK: "\\mathbf{lK}",
	    bSilK: "\\mathbf{SilK}",
	    bCPL: "\\mathbf{CPL}",
	    bRal: "\\mathbf{Ral}",
	    bgK: "\\mathbf{gK}",
	    bFm: "\\mathbf{Fm}",
	    bPML: "\\mathbf{PML}",
	    bMA: "\\mathbf{MA}",
	    bRMatr: "\\mathbf{RMatr}",
	    bILL: "\\mathbf{ILL}",
	    bIL: "\\mathbf{IL}",
    	    bILsubZ: "\\mathbf{IL_0}",
	    bL: "\\mathbf{L}",
	    bR: "\\mathbf{R}",
	    bA: "\\mathbf{A}",
	    bM: "\\mathbf{M}",
	    bB: "\\mathbf{B}",
	    bK: "\\mathbf{K}",
	    bv: "\\boldsymbol{v}",
	    bsigma: "\\mathbf{\\sigma}",
	    bOmega: "\\mathbf{\\Omega}",
	    cB: "\\mathcal{B}",
	    cM: "\\mathcal{M}",
	    cA: "\\mathcal{A}",
	    cC: "\\mathcal{C}",
	    txtiff: "\\;\\textrm{ iff }\\;",
	    tTH: "\\textrm{Th}",
	    tMP: "\\textrm{MP}",
	    tR: "\\textrm{R}",
	    tD: "\\mathrm{D}",
	    tE: "\\mathrm{E}",
	    tS: "\\textrm{S}",
	    tT: "\\textrm{T}",
	    tRe: "\\textrm{Re}",
	    tFi: "\\textrm{Fi}",
	    tEq: "\\textrm{Eq}",
	    iEq: "\\textit{Eq}",
	    blLambda: "\\mathbf{l\\Lambda}",
	    bgLambda: "\\mathbf{g\\Lambda}",
        }
    }
};
