window.MathJax = {
    TeX: {
        TagSide: "left",
        TagIndent: "0em",
        Macros: {
	    amp: "\\mathbin{\\&}",
            bfrac: ["{^{#1}\\unicode{x2044}_{#2}}",2],
	    frasl: "\\unicode{x2044}",
	    Diamond: "\\unicode{x2B26}",
	    dproves: "\\mathbin{\\rvert\\!{\\sim}}",
	    notdproves: "\\mathop{\\mathrel{\\rlap{\\hskip .2em/}}\\rvert\\!{\\sim}}",
	    llbracket: "[\\![",
	    rrbracket: "]\\!]",
	    boxright: "\\mathbin{{\\square}\\kern-1.5pt{\\raise.7pt{\\rightarrow}}}",
	    bA: "\\mathbf{A}",
	    bB: "\\mathbf{B}",
	    bC: "\\mathbf{C}",
	    bG: "\\mathbf{G}",
	    bI: "\\mathbf{I}",
	    bV: "\\mathbf{V}",
	    bS: "\\mathbf{S}",
	    bW: "\\mathbf{W}",
	    bX: "\\mathbf{X}",
	    bx: "\\mathbf{x}",
	    by: "\\mathbf{y}",
	    bz: "\\mathbf{z}",
	    bY: "\\mathbf{Y}",
	    bU: "\\mathbf{U}",
	    bZ: "\\mathbf{Z}",
	    bPA: "\\textbf{PA}",
	    bDE: "\\textbf{DE}",
	    ido: "\\textit{do}",
	    Pr: "\\mathrm{P}",
	    Ur: "\\mathrm{U}",
	    EEU: "\\mathrm{EEU}",
	    CEU: "\\mathrm{CEU}",
	}
    }
};
