window.MathJax = {
    TeX: {
        TagSide: "right",
        TagIndent: "0em",
        Macros: {
            AM: "{\\mathsf{AM}}",
	    AMC: "{\\mathsf{AM}{+}C}",
	    AMS: "{{\\mathsf{AM{+}S}}}",
	    APAL: "{\\mathsf{APAL}}",
            APUL: "{\\mathsf{APUL}}",
	    arr: "{\\,{\\gg}\\,}",
	    arrp: "{\\,{\\gg}'\\,}",
	    At: "{\\mathsf{At}}",
	    bisim: "\\mathrel{\\overset{\\leftrightarrow}{\\_}}",
	    CaU: "{\\mathsf{CaU}}",
            cc: "{\\mathsf{cc}}",
            CDL: "{\\mathsf{CDL}}",
	    Cl: "{\\mathsf{Cl}}",
	    col: "{\\,{:}\\,}",
	    con: "{\\mathsf{con}}",
	    CPAM: "{\\mathsf{CPAM}}",
            CU: "{\\mathsf{CU}}",
            DEL: "{\\mathsf{DEL}}",
	    DEUL: "{\\mathsf{DEUL}}",
            EAL: "{\\mathsf{EAL}}",
	    EALC: "{\\mathsf{EAL}{+}C}",
	    EALS: "{\\mathsf{EAL{+}S}}",
	    EUM: "{\\mathsf{EUM}}",
            GDDL: "{\\mathsf{GDDL}}",
	    GML: "{\\mathsf{GML}}",
            JBG: "{\\mathsf{JBG}}",
            KBox: "{\\mathsf{K}\\Box}",
            L: "{\\mathsf{L}}",
	    Lang: "{\\mathcal L}",
            LCC: "{\\mathsf{LCC}}",
            LEAL: "{(\\mathsf{L}{+}\\text{EAL})}",
            LPAL: "{(\\L\\text{+PAL})}",
	    LRCKP: "{(\\L\\text{+RCK+P})}",
	    may: ["{\\langle}{#1}{\\rangle}",1],
            MPri: "{\\mathsf{MPri}}",
            PAL: "{\\mathsf{PAL}}",
            PALC: "{\\mathsf{PAL}{+}C}",
            PAM: "{\\mathsf{PAM}}",
            pre: "{\\mathsf{pre}}",
            Pri: "{\\mathsf{Pri}}",
	    Pub: "{\\mathsf{Pub}}",
	    RCK: "{\\mathsf{RCK}}",
	    RCKP: "{\\mathsf{RCK{+}P}}",
	    rPri: "{\\mathsf{rPri}}",
	    rPub: "{\\mathsf{rPub}}",
            sA: "{\\mathcal A}",
            sC: "{\\mathcal C}",
            sem: ["{\\lbrack\\!\\lbrack{#1}\\rbrack\\!\\rbrack}",1],
            sP: "{\\mathcal P}",
	    sub: "{\\mathsf{sub}}",
            taglabel: ["{\\tag{#1}\\label{#1}}",1],
	    Up: ["{\\Uparrow}"],
	    up: ["{\\uparrow}"],
	    coloneqq:  ["{\\mathrel{\\;:=\\;}}"],
    	    ccoloneqq:  ["\\;{\\mathrel{::=}}\\;"],
        }
    }, 
    "HTML-CSS": { linebreaks: { automatic: true } },
    "SVG": { linebreaks: { automatic: true } },
};
