window.MathJax = {
    TeX: {
        TagSide: "left",
        TagIndent: "0em",
        Macros: {
	    amp: "\\mathbin{\\&}",
	    monus: "\\mathop{\\unicode{8760}}",
	    Hy: "\\textrm{-}",
	    proof: "\\textsf{Proof}",
	    sfPr: "\\textsf{Pr}",
	    iproof: "\\operatorname{\\textit{proof}}",
	    igen: "\\textit{gen}",
	    rproof: "\\textrm{PROOF}",
	    rform: "\\textrm{form}",
	    rCODE: "\\textrm{CODE}",
	    ATR: "\\textbf{ATR}",
	    ACA: "\\textbf{ACA}",
	    PRA: "\\textbf{PRA}",
	    WKL: "\\textbf{WKL}",
	    bPi: "\\mathbf{\\Pi}",
    	    KP: "\\mathbf{KP}",
	    PA: "\\textbf{PA}",
	    WQO: "\\textrm{WQO}",
	    RCA: "\\textbf{RCA}",
	    Con: "\\textrm{Con}",
	    rAcc: "\\textrm{Acc}",
	    bF: "\\mathbf{F}",
	    bID: "\\textbf{ID}",
	    zL: "\\mathbf{L}",
	    bL: "\\mathrm{L}",
	    bN: "\\mathbf{N}",
	    bR: "\\mathbf{R}",
	    bS: "\\mathbf{S}",
	    bT: "\\mathbf{T}",
	    bZ: "\\mathbf{Z}",
	    bRA: "\\textbf{RA}",
	    bbA: "\\mathbb{A}",
	    bbB: "\\mathbb{B}",
	    bbN: "\\mathbb{N}",
	    bbR: "\\mathbb{R}",
	    fE: "\\mathfrak{E}",
	    fraka: "\\mathfrak{a}",
	    frakb: "\\mathfrak{b}",
	    frakA: "\\mathfrak{A}",
	    fB: "\\mathfrak{B}",
	    fN: "\\mathfrak{N}",
	    fP: "\\mathfrak{P}",
	    rR: "\\mathrm{R}",
	    rL: "\\mathrm{L}",
	    rS: "\\mathrm{S}",
	    rT: "\\mathrm{T}",
	    rW: "\\mathrm{W}",
	    cB: "\\mathcal{B}",
	    cK: "\\mathcal{K}",
	    rK: "\\mathrm{K}",
	    cT: "\\mathcal{T}",
	    cL: "\\mathcal{L}",
	    cD: "\\mathcal{D}",
	    cH: "\\mathcal{H}",
	    cO: "\\mathcal{O}",
	    relLTcO: "\\mathrel{<_{\\lower{.5ex}{\\scriptscriptstyle\\mathcal{O}}}}",
	    cR: "\\mathcal{R}",
	    cC: "\\mathcal{C}",
	    BI: "\\textbf{BI}",
	    PL: "\\textbf{PL}",
	    ZFC: "\\textbf{ZFC}",
	    bCA: "\\textbf{CA}",
	    bCR: "\\textbf{CR}",
	    bAC: "\\textbf{AC}",
	    rAC: "\\textrm{AC}",
	    rACC: "\\textrm{ACC}",
	    rIP: "\\textrm{IP}",
	    bBR: "\\textbf{BR}",
	    rBR: "\\textrm{BR}",
	    rTI: "\\textrm{TI}",
	    bHA: "\\textbf{HA}",
            ON: "\\textit{ON}",
	    rlim: "\\operatorname{lim}",
	    rsuc: "\\textrm{suc}",
	    iTran: "\\textit{Tran}",
	    iRef: "\\textit{Ref}",
            sCNF: "{\\scriptscriptstyle \\textit{CNF}}",
	    sOmega: "\\scriptscriptstyle \\Omega",
	    ssfB: "{\\scriptscriptstyle\\mathfrak{B}}",
	    ssM: "{\\scriptscriptstyle M}",
	    qf: "\\textit{qf}",
	    ord: "\\operatorname{\\textit{ord}}",
	    coloneqq: "\\mathbin{:=}",
	    stile: ["\\mathbin{|\\hspace{-3pt}\\scriptstyle\\begin{array}{l}#1\\\\\\hline#2\\end{array}}", 2],
	    Corner: ["\\mathord{\\ulcorner #1\\urcorner}",1],
	    ldot: "\\mathord{.}",
	    qed: "\\Box",
	    iddots: "\\unicode{x22F0}"
	}
    }
};
